name: Documentation
on:
  push:
    branches:
      - master
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.13"
        enable-cache: true
        cache-suffix: uv-${{ runner.os }}-3.13

    - name: Install dependecies
      run: uv sync --all-groups

    - name: Set up build cache
      uses: actions/cache/restore@v4
      with:
        key: mkdocs-${{ hashfiles('.cache/**') }}
        path: .cache
        restore-keys: |
          mkdocs-

    - name: Build documentation
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        uv run mkdocs build --clean

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

    - name: Save build cache
      uses: actions/cache/save@v4
      with:
        key: mkdocs-${{ hashfiles('.cache/**') }}
        path: .cache


